name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-project:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.13] # Укажите версию Node.js, необходимую вашему проекту

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      # Настройка окружения Pages на стороне GitHub
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Загрузка результатов сборки в хранилище GitHub Artifacts
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # ВАЖНО: Укажите папку, в которую ваш проект собирает файлы.
          # Для Vite / Vue / React это обычно 'dist', для старых версий React 'build', для Next.js 'out'.
          path: "./dist"

      # Публикация файлов на хостинг GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
